<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "kidsfood".
 *
 * @property integer $id
 * @property string $category_name
 * @property string $name
 * @property string $description
 * @property double $price
 * @property string $cook
 * @property integer $weight
 * @property string $img
 */
class Kidsfood extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kidsfood';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['price'], 'number'],
            [['weight'], 'integer'],
            [['category_name', 'name', 'description', 'cook', 'img'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_name' => 'Категория',
            'name' => 'Название блюда',
            'description' => 'Описание',
            'price' => 'Цена',
            'cook' => 'Способ приготовления',
            'weight' => 'Вес',
            'img' => 'Картинка',
        ];
    }
    public function saveImage($filename)
    {
        $this->img = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->img) ? '/images/' . $this->img : '/no-image.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->img);
    }


    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
